git checkout modules.dot
git checkout modules.pdf
git checkout modules_neato.pdf
git checkout modules_radial.pdf
git checkout modules_analogue.pdf
git checkout modules_comms.pdf
git checkout modules_computing.pdf
git checkout modules_control.pdf
git checkout modules_devices.pdf
git checkout modules_digital.pdf
git checkout modules_fields.pdf
git checkout modules_maths.pdf
git checkout modules_ml.pdf
git checkout modules_power.pdf
git checkout modules_prof.pdf
git checkout modules_robotics.pdf
git checkout modules_signals.pdf
git checkout modules_with_root.dot
git checkout table.html
git pull --rebase
git push
