name: Build dependency graph
on: push
jobs:
  run-all:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check modules.yml is valid YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: modules.yml
          config_data: |
            rules:
              line-length:
                max: 200
                level: warning
              trailing-spaces:
                level: warning
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get -y install graphviz opam
          opam init
          opam install --yes dune
          opam install --yes yaml
      - name: Build the dependency graph
        run: |
          eval $(opam env)
          make themes
	  make table
      - name: Add dependency graph to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "Recreating .dot, .pdf, and .html files"
          file_pattern: 'modules*.pdf modules*.dot table.html'
          push_options: --force
