name: Graphviz
on: push
jobs:
  run-all:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get -y install graphviz
      - name: Build the dependency graph
        run: make
      - name: Add dependency graph to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Recreating modules.pdf
          file_pattern: 'modules.pdf'
          push_options: --force
